version: "3.8"

services:
  frontend:
    build:
      target: build
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development

  backend:
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=secure_file_share.settings.development
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
